# Generated by Django 5.2.17 on 2026-09-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("color", models.CharField(max_length=64)),
                ("display_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CustomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "schema_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("kind", models.CharField(max_length=16)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("values_defined", models.BooleanField(default=False)),
                ("values_null", models.BooleanField(default=False)),
                ("fields_defined", models.BooleanField(default=False)),
                ("fields_null", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Diagram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("database_type", models.CharField(max_length=32)),
                (
                    "database_edition",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-updated_at", "external_id"],
            },
        ),
        migrations.CreateModel(
            name="CustomTypeField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("type_name", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField()),
                (
                    "custom_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="diagrams.customtype",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CustomTypeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField()),
                ("position", models.PositiveIntegerField()),
                (
                    "custom_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="diagrams.customtype",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="DBTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                (
                    "schema_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("color", models.CharField(max_length=64)),
                ("is_view", models.BooleanField(default=False)),
                ("is_materialized_view", models.BooleanField(blank=True, null=True)),
                ("client_created_at", models.BigIntegerField()),
                ("width", models.FloatField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                ("expanded", models.BooleanField(blank=True, null=True)),
                ("check_constraints_defined", models.BooleanField(default=False)),
                ("check_constraints_null", models.BooleanField(default=False)),
                (
                    "parent_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tables",
                        to="diagrams.area",
                    ),
                ),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="diagrams.diagram",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="DBIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("unique", models.BooleanField(default=False)),
                ("client_created_at", models.BigIntegerField()),
                ("index_type", models.CharField(blank=True, max_length=32, null=True)),
                ("is_primary_key", models.BooleanField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indexes",
                        to="diagrams.dbtable",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="DBField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                ("type_id", models.CharField(max_length=255)),
                ("type_name", models.CharField(max_length=255)),
                ("primary_key", models.BooleanField(default=False)),
                ("unique", models.BooleanField(default=False)),
                ("nullable", models.BooleanField(default=False)),
                ("increment", models.BooleanField(blank=True, null=True)),
                ("is_array", models.BooleanField(blank=True, null=True)),
                ("client_created_at", models.BigIntegerField()),
                (
                    "character_maximum_length",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("precision", models.IntegerField(blank=True, null=True)),
                ("scale", models.IntegerField(blank=True, null=True)),
                ("default_value", models.TextField(blank=True, null=True)),
                ("collation", models.CharField(blank=True, max_length=255, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("check_expression", models.TextField(blank=True, null=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="diagrams.dbtable",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="CheckConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                ("expression", models.TextField()),
                ("client_created_at", models.BigIntegerField()),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_constraints",
                        to="diagrams.dbtable",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "schema_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dependent_schema",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("client_created_at", models.BigIntegerField()),
                (
                    "dependent_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_on",
                        to="diagrams.dbtable",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="diagrams.dbtable",
                    ),
                ),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        to="diagrams.diagram",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddField(
            model_name="customtype",
            name="diagram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_types",
                to="diagrams.diagram",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="diagram",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="diagrams.diagram",
            ),
        ),
        migrations.CreateModel(
            name="DiagramFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("schema_ids_defined", models.BooleanField(default=False)),
                ("schema_ids", models.JSONField(default=list)),
                ("table_ids_defined", models.BooleanField(default=False)),
                ("table_ids", models.JSONField(default=list)),
                (
                    "diagram",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagram_filter",
                        to="diagrams.diagram",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndexField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_memberships",
                        to="diagrams.dbfield",
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="index_fields",
                        to="diagrams.dbindex",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                ("content", models.TextField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("width", models.FloatField()),
                ("height", models.FloatField()),
                ("color", models.CharField(max_length=64)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="diagrams.diagram",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64)),
                ("position", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
                (
                    "source_schema",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "target_schema",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("source_cardinality", models.CharField(max_length=8)),
                ("target_cardinality", models.CharField(max_length=8)),
                ("client_created_at", models.BigIntegerField()),
                (
                    "diagram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships",
                        to="diagrams.diagram",
                    ),
                ),
                (
                    "source_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_relationships",
                        to="diagrams.dbfield",
                    ),
                ),
                (
                    "source_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_relationships",
                        to="diagrams.dbtable",
                    ),
                ),
                (
                    "target_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_relationships",
                        to="diagrams.dbfield",
                    ),
                ),
                (
                    "target_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_relationships",
                        to="diagrams.dbtable",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
        migrations.AddConstraint(
            model_name="dbindex",
            constraint=models.UniqueConstraint(
                fields=("table", "external_id"), name="unique_index_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="dbfield",
            constraint=models.UniqueConstraint(
                fields=("table", "external_id"), name="unique_field_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="checkconstraint",
            constraint=models.UniqueConstraint(
                fields=("table", "external_id"), name="unique_check_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="dependency",
            constraint=models.UniqueConstraint(
                fields=("diagram", "external_id"), name="unique_dependency_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="dbtable",
            constraint=models.UniqueConstraint(
                fields=("diagram", "external_id"), name="unique_table_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="customtype",
            constraint=models.UniqueConstraint(
                fields=("diagram", "external_id"), name="unique_custom_type_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                fields=("diagram", "external_id"), name="unique_area_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="indexfield",
            constraint=models.UniqueConstraint(
                fields=("index", "field"), name="unique_index_field"
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(
                fields=("diagram", "external_id"), name="unique_note_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.UniqueConstraint(
                fields=("diagram", "external_id"), name="unique_relationship_id"
            ),
        ),
    ]
